# Generated by Django 6.0.2 on 2026-03-09 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_empquery_reply'),
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Item_name', models.CharField(max_length=20)),
                ('Item_desc', models.CharField(max_length=30)),
                ('Item_price', models.IntegerField()),
                ('Item_image', models.ImageField(null=True, upload_to='image')),
                ('Item_color', models.CharField(max_length=20)),
                ('Item_Qty', models.IntegerField()),
                ('Item_category', models.CharField(max_length=20)),
            ],
        ),
    ]
